language: node_js
node_js:
  - 12
branches:
  only:
    - master
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT
install:
  - npm install
after_success:
  - npm run lh -- https://shogosensui.com
